{% set version = "1.03.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gsa
  version: {{ version|replace("-", "_") }}

source:
  fn: GSA_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/GSA_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/GSA/GSA_{{ version }}.tar.gz
  sha256: e192d4383f53680dbd556223ea5f8cad6bae62a80a337ba5fd8d05a8aee6a917

build:
  noarch: generic
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('GSA')"  # [not win]
    - "\"%R%\" -e \"library('GSA')\""  # [win]

about:
  home: http://www-stat.stanford.edu/~tibs/GSA
  license: LGPL
  summary: Gene set analysis
  license_family: LGPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
