travis:
  secure:
    BINSTAR_TOKEN: A8BIf92X7BsZi+dfRHn/j08/ssKvj7VdAoGMmq+imKd6eVL4UrlOlLzYwX5ZB9AW5EDZWjgB3EAPmLBoBH4+AlQ3dsfdSgfsIKvDf5ZstV9CFbT2FPaghXVFo/43pA2QoNKjHoGEyAkMM5yvlq2ncfBE9uQWBsMvct2ZavG6qlzrsMN5t/21uOD+U8OZesASQp16lJ+o6v7DFEdSkbN171Mdnq8NqS925s2lnAJD/s0JNVTfi55kjjZWd283Xizj11SC1vC6nhdGF303L1Ren39dRFmKewOfUgmXYDJDJhuZdtqJZ2Xtq4MMtgVvet6RZ2WqPUHgyvuH3L2f2Hgyf2IF0lrlfaVpZS3lskpaBgAVkmUtc+EDWx2KndEfSfgCZbEQ5aqr4EH9ABblG5UXbTmgroniKgAMo/wW72EjLFxNUwU2kJhAk5j6uFOb8f/XiVzZZVvebxzzm2bz+PswxtSSQ//opGWKR6tOH35cKI+pA3F6z8ul82sApm7g2IQHfGd0wS7+4vv0rmEw99/7JeqjphPq8I/pfszEWxJFKeigQ5/ROQXTS9kYtaQ2J+FjVM/W+CZV6bw17W/7dEIgqzjriJZCrMAWZqZ0N01M153d/v4060TjqWNyQpGOjEHwSZQ/SX37nB7Xwe6RDcRBiDJb+ncEow/9N9DtJsu3XoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
