appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OnF2aYLh0/tVIIT8uWIwEoI2CGQr9NcADvmeebDEfU7qoTXiybg93s3pnMSNgQscbWTcgpl+imYbn0W+EdOA9gR1IGS1ZTqA19WZWk1+HE4SP+De7HsERmaWkWiYAUAZMVQ/PZZ6EPnkFC87ixhpy/42I4wI8RO0Kt4UixEFBbFWmZYjDgtbm9d+sfW77WC29FmkB6pywrSKNHOaq8J50kQacNQvgKaDwjPOP5xDOEaYu5CIdcIrMTJ36KNdmCi2NEXIkF+NJ1R1O26Q6l1bwE/VpkfbDkFR8wYTcwnoq3zkTjyLxYP+Mrl2iMrNlrLO176Z5zXLetYnzgY97zDbcjjcB+aZuu1+e/dqDDg7JSm1JB45FscjyEin2qBvKEYecGkkvQEzCmkuLt3pcseUekyZRgL6IIxS0MOOfOjuLb2VKNslKqmf+MmATdWdpBI7Er9Ydaz2X3VIJQEhhhVyCfYUEEBd631M+p97cxLta9wAlNayZIkx/w2vhCE+dSLOkLdDcDM3S1G5EGKXZH0UjiwcZFwmbgkJY0Q3yZWkdQoVnmQPBMNXzOrrg4JWJ2ujEzXxr9XtC2Lw1EWcUlbkSscspmAHyAx11L9rKttpoyTCFdgGCe9e4Ka43/t8FM7qCuQ0vWjhl9jWOCaDgZSwlgHqXExfuh0Db6GA4UcoX8E=
