travis:
  secure:
    BINSTAR_TOKEN: npjwqHL+f7Dv2UnmnSOl+D1t4uVzf6lDNkQApEqOhBZI06vXIrNKaYCCPkG+JwUr2jC5B6cDsfEF05OlgE+fEKPVEBBtl72Qa6q7kvcw5FSjsC+oyfdK8np2Qqq1eHbV84oM5v2I9tjuSKP7NK5mr7pcY4BbWiXrqwZ43xd2MxlcdxizBLMxwwX1B+JxnAGCgRrugZ5lkTw41f6pJhNC/lsx7SlAPVCpL11tqdnCf/9cwAy3Bnu4xK01LJcMXWViiXTYx8UCehXSQGPabiVy2tJYbxQnv4E+DZD7WxkSVJb8PrctM70RRuGqYI+pWMHq5TD8dEMuWeURH7k6t7u8Qc2eKsAVzgAXBHi3kYDfsC5Z0e3hbTZCHKO4EOhX8dxiUqzgj4v6fzyALBCMo6D7gqe3ELoferOtu4OeqvpkUareD44TfxJn+5d826dJACbWDo8DfoeTK+DLhJfftjjXVIeQgh8R6EoGQDvVP2UJcwx5TXGPh6AsFlgRsBZHPJphbq7GjKZy4Y7KRQGggbASoSdGXboAQKCjYu3w3ZTxkK3NceMghx61uN7DjmR4mFAkzPANMHLwmb+uvIT92H/1HTN1zhBJQQcnVtN6DBKAkKHj8oCwZP4CeuJaqjLv/+6BROecjhPUb/c2EXmgmHud0vFsLA9DHdcEe6IdTtJIRe0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
